name: emm_pay
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.10
  shimmer: ^3.0.0
  easy_localization: ^3.0.7
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
#  flutter_launcher_icons: ^0.14.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
#  image_path: "assets/icons/launcher_icon.png"
  image_path: "assets/images/pngs/visa-card.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/pngs/
    - assets/images/svgs/
    - assets/translations/
